AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/**/*
    - config.ru
    - Guardfile
    - Rakefile
    - app/channels/**/*
    - Gemfile

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 15
  Exclude:
    - app/controllers/**/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PredicateName:
  Exclude:
    - lib/active_model_serializers_matchers/**/*

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
